packages:
  - packages/core
  - packages/thumbnail
  - packages/renderers/*
  - packages/presets/*
  - packages/tools/*
  - packages/components/*
  - packages/compat/*
  - apps/*
  - examples/vanilla-vite
  - examples/react-vite
  - examples/vue3-vite

peerDependencyRules:
  allowedVersions:
    '@types/react': '>=17 <20'
    react: '>=17 <20'
    react-dom: '>=17 <20'

allowBuilds:
  '@parcel/watcher': true
  ant-design-vue: true
  canvas: true
  core-js: true
  es5-ext: true
  esbuild: true
  fsevents: true

overrides:
  '@file-viewer/example-vanilla-vite>@file-viewer/web': workspace:2.2.0
  '@file-viewer/example-vanilla-vite>@file-viewer/preset-lite': workspace:2.2.0
  '@file-viewer/example-vanilla-vite>@file-viewer/vite-plugin': workspace:2.2.0
  '@file-viewer/example-react-vite>@file-viewer/react': workspace:2.2.0
  '@file-viewer/example-react-vite>@file-viewer/preset-office': workspace:2.2.0
  '@file-viewer/example-react-vite>@file-viewer/vite-plugin': workspace:2.2.0
  '@file-viewer/example-vue3-vite>@file-viewer/vue3-full': workspace:2.2.0
  '@file-viewer/example-vue3-vite>@file-viewer/preset-all': workspace:2.2.0
  '@file-viewer/example-vue3-vite>@file-viewer/vite-plugin': workspace:2.2.0
