import { computed, type Ref } from 'vue'

export type DemoLocale = 'zh-CN' | 'en-US'
export type DemoCopy = Record<string, string>

const demoCopyMap: Record<DemoLocale, DemoCopy> = {
  'zh-CN': {
    pageTitle: 'Flyfish File Viewer 在线预览器 Vue3',
    pureWeb: 'Pure Web',
    local: '本地',
    link: '链接',
    pasteLink: '粘贴链接',
    upload: '上传',
    samples: '样例',
    search: '搜索',
    more: '更多',
    home: '首页',
    previewWorkspace: '返回预览工作区',
    openFile: '打开文件',
    openFromLink: '从链接打开',
    openFromDevice: '从设备上传',
    browseSamples: '浏览样例',
    settings: '设置',
    fullSettings: '完整设置',
    settingsTitle: '预览设置',
    settingsDescription: '调整当前文件的展示细节',
    settingsDisplayTab: '显示',
    settingsToolbarTab: '工具栏与搜索',
    settingsFormatsTab: '格式能力',
    closeSettings: '关闭预览设置',
    displaySettings: '显示与布局',
    themeMode: '主题模式',
    systemTheme: '跟随系统',
    lightTheme: '浅色',
    darkTheme: '深色',
    styleIsolation: '样式隔离',
    density: '界面密度',
    comfortable: '舒适',
    compact: '紧凑',
    surfaceBackground: '页面之外背景',
    surfaceTransparent: '沉浸透明',
    surfaceDefault: '格式默认',
    fitPadding: '页面留白',
    fitResize: '自适应策略',
    fitUntilInteraction: '交互前保持',
    fitAlways: '始终保持',
    fitInitial: '仅首次',
    fitScaleRange: '缩放范围',
    watermarkSettings: '水印',
    watermarkText: '水印文字',
    watermarkOpacity: '透明度',
    watermarkRotation: '旋转角度',
    watermarkSpacing: '横向 / 纵向间距',
    watermarkFontSize: '字号',
    watermarkColor: '颜色',
    externalToolbarSettings: '外部工具栏',
    externalToolbarHint: '完整保留原 Demo 能力，并通过公开 API 驱动预览器。',
    searchSettings: '搜索行为',
    enableSearch: '启用文档搜索',
    caseSensitive: '区分大小写',
    wholeWord: '全词匹配',
    maxMatches: '最多结果',
    showSearch: '搜索',
    showZoom: '缩放',
    showDownload: '下载',
    showPrint: '打印',
    showExportHtml: 'HTML 导出',
    formatSettings: '当前格式',
    formatSelector: '配置格式',
    currentFormat: '当前文件',
    pdfFormat: 'PDF',
    wordFormat: 'Word',
    sheetFormat: '表格',
    textFormat: '文本 / 代码',
    archiveFormat: '压缩包',
    cadFormat: 'CAD',
    geoFormat: '地理数据',
    modelFormat: '三维模型 / STEP',
    modelSettingsHint: '以下 OCCT 解析设置用于 STEP、IGES 与 BREP。',
    drawingFormat: '绘图',
    visualPagination: '模拟分页',
    progressiveRendering: '渐进渲染',
    strictWordCompatibility: '严格 Word 兼容',
    awaitLayout: '等待布局稳定',
    hideWebHiddenContent: '隐藏 Web 隐藏内容',
    ignoreLastPageBreak: '忽略上次分页符',
    pdfToolbar: 'PDF 内置工具栏',
    pdfNavigation: '导航面板',
    defaultNavigationVisible: '默认展开导航',
    pdfThumbnails: '页面缩略图',
    pdfRotation: '初始旋转',
    pdfStreaming: '流式加载',
    cjkFontFallback: 'CJK 字体回退',
    identityFontRepair: 'Identity 字体修复',
    resizableColumns: '允许拖拽列宽',
    resizableRows: '允许拖拽行高',
    textEncoding: '文本编码',
    workerThreshold: 'Worker 阈值',
    textToolbar: '文本源信息栏',
    lineNumbers: '显示行号',
    virtualizeThreshold: '虚拟渲染阈值',
    markdownVirtualizeThreshold: 'Markdown 源码阈值（0 保持排版）',
    maxRenderedLine: '单行渲染上限',
    overscanLines: '预渲染行数',
    archiveCache: '缓存解压结果',
    archiveEntryDownload: '允许下载内部文件',
    maxArchiveSize: '压缩包大小上限',
    maxEntryPreview: '内部预览上限',
    cadRenderer: '渲染器',
    cadFitMode: '初始适配',
    cadFitPadding: '图纸占比',
    includePaperSpace: '包含图纸空间',
    lineWeightMode: '线宽模式',
    bestFit: '智能边界',
    nativeBounds: '原始边界',
    geoBasemap: '底图',
    inferProjection: '自动推断坐标系',
    preferMapEngine: '优先地图引擎',
    geoFitPadding: '边界留白',
    modelUseWorker: '在 Worker 中解析',
    modelWorkerTimeout: '解析超时',
    modelLinearUnit: '线性单位',
    modelUnitMillimeter: '毫米 (mm)',
    modelUnitCentimeter: '厘米 (cm)',
    modelUnitMeter: '米 (m)',
    modelUnitInch: '英寸 (in)',
    modelUnitFoot: '英尺 (ft)',
    modelDeflectionType: '线性偏差方式',
    modelDeflectionRatio: '包围盒比例',
    modelDeflectionAbsolute: '绝对值',
    modelLinearDeflection: '线性偏差',
    modelAngularDeflection: '角度偏差（弧度）',
    preferOfficialDrawing: '优先官方绘图运行时',
    reloadHint: '应用后会安全刷新预览，并恢复当前位置。',
    noFormatSettings: '该格式当前使用推荐默认值。',
    resetDefaults: '恢复默认',
    cancel: '取消',
    applySettings: '应用设置',
    settingsApplied: '设置已应用',
    settingsApplyFailed: '设置未能应用，请检查参数后重试',
    integration: '接入',
    toggleSourcePanel: '切换文件面板',
    quickSamples: '快速试用',
    quickSamplesHint: '常用格式一键打开',
    sampleFile: '示例文件',
    collapse: '收起',
    open: '打开',
    address: '地址',
    addressPlaceholder: '输入文件地址',
    linkPanelTitle: '从链接打开',
    linkPanelHint: '支持相对路径、子目录和完整 URL',
    uploadPanelTitle: '从设备上传',
    uploadPanelHint: '文件只在当前浏览器中处理，不会上传到服务器',
    samplesPanelTitle: '示例文件库',
    preview: '预览',
    closePanel: '关闭操作面板',
    chooseFile: '点击选择文件',
    openLocal: '从本机打开',
    recentOpened: '最近打开',
    closeRecent: '关闭最近打开',
    showRecent: '显示最近打开',
    openRecent: '打开',
    dismissRecent: '从最近打开中移除',
    reselectLocalFile: '浏览器不会长期保存本地文件，请重新选择“{name}”',
    unselected: '未选择文件',
    documentInfo: '文档信息',
    closeDocumentInfo: '关闭文档信息',
    fileSource: '来源',
    filePath: '路径',
    fileFormat: '格式',
    previewActions: '预览操作',
    zoomControls: '缩放控制',
    zoomOut: '缩小预览',
    zoomIn: '放大预览',
    resetZoom: '还原比例',
    fitMode: '适配',
    fitDefault: '默认',
    fitAuto: '自动',
    fitContain: '完整',
    fitCover: '铺满',
    fitWidth: '宽度',
    fitHeight: '高度',
    fitActual: '100%',
    fitScaleDown: '缩小',
    download: '下载',
    downloadTitle: '下载原始文件',
    print: '打印',
    printTitle: '打印完整渲染内容',
    printDirect: '直接打印',
    printMask: '掩膜打印',
    printMaskTitle: '遮盖敏感区域后再打印',
    exportHtml: 'HTML',
    exportHtmlTitle: '导出当前渲染后的 HTML',
    watermark: '水印',
    watermarkTitle: '切换水印',
    searchDocument: '文档搜索',
    searchPlaceholder: '搜索当前文档',
    previousResult: '上一个搜索结果',
    nextResult: '下一个搜索结果',
    closeSearch: '关闭搜索',
    closeMobileControls: '关闭移动端操作面板',
    openLinkSettings: '打开链接设置',
    openSamples: '打开示例文件',
    uploadLocalFile: '上传本地文件',
    searchCurrentDocument: '搜索当前文档',
    openMoreActions: '打开更多操作',
    reset: '还原',
    auto: 'AUTO',
    language: '语言',
    theme: '主题',
    themeToLight: '切换为浅色模式',
    themeToDark: '切换为深色模式',
    integrationSnippet: '接入代码',
    openIntegrationSnippet: '查看接入代码',
    integrationSnippetHint: '在浮层中查看并复制示例',
    integrationSnippetDescription: 'React 完整接入示例',
    closeIntegrationSnippet: '关闭接入代码',
    copySnippet: '复制代码',
    copiedSnippet: '已复制'
  },
  'en-US': {
    pageTitle: 'Flyfish File Viewer Demo for Vue 3',
    pureWeb: 'Pure Web',
    local: 'Local',
    link: 'URL',
    pasteLink: 'Paste link',
    upload: 'Upload',
    samples: 'Samples',
    search: 'Search',
    more: 'More',
    home: 'Home',
    previewWorkspace: 'Return to preview workspace',
    openFile: 'Open file',
    openFromLink: 'Open from URL',
    openFromDevice: 'Upload from device',
    browseSamples: 'Browse samples',
    settings: 'Settings',
    fullSettings: 'Full settings',
    settingsTitle: 'Preview settings',
    settingsDescription: 'Tune how the current file is presented',
    settingsDisplayTab: 'Display',
    settingsToolbarTab: 'Toolbar & search',
    settingsFormatsTab: 'Format options',
    closeSettings: 'Close preview settings',
    displaySettings: 'Display & layout',
    themeMode: 'Theme mode',
    systemTheme: 'System',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    styleIsolation: 'Style isolation',
    density: 'Interface density',
    comfortable: 'Comfortable',
    compact: 'Compact',
    surfaceBackground: 'Outside-page background',
    surfaceTransparent: 'Immersive',
    surfaceDefault: 'Format default',
    fitPadding: 'Page padding',
    fitResize: 'Responsive fit',
    fitUntilInteraction: 'Until interaction',
    fitAlways: 'Always',
    fitInitial: 'Initial only',
    fitScaleRange: 'Scale range',
    watermarkSettings: 'Watermark',
    watermarkText: 'Watermark text',
    watermarkOpacity: 'Opacity',
    watermarkRotation: 'Rotation',
    watermarkSpacing: 'Horizontal / vertical gap',
    watermarkFontSize: 'Font size',
    watermarkColor: 'Color',
    externalToolbarSettings: 'External toolbar',
    externalToolbarHint: 'Keeps every original demo action and drives the viewer through its public API.',
    searchSettings: 'Search behavior',
    enableSearch: 'Enable document search',
    caseSensitive: 'Case sensitive',
    wholeWord: 'Whole word',
    maxMatches: 'Maximum matches',
    showSearch: 'Search',
    showZoom: 'Zoom',
    showDownload: 'Download',
    showPrint: 'Print',
    showExportHtml: 'HTML export',
    formatSettings: 'Current format',
    formatSelector: 'Configure format',
    currentFormat: 'Current file',
    pdfFormat: 'PDF',
    wordFormat: 'Word',
    sheetFormat: 'Spreadsheet',
    textFormat: 'Text / code',
    archiveFormat: 'Archive',
    cadFormat: 'CAD',
    geoFormat: 'Geospatial',
    modelFormat: '3D model / STEP',
    modelSettingsHint: 'These OCCT parsing controls apply to STEP, IGES, and BREP.',
    drawingFormat: 'Drawing',
    visualPagination: 'Visual pagination',
    progressiveRendering: 'Progressive rendering',
    strictWordCompatibility: 'Strict Word compatibility',
    awaitLayout: 'Wait for stable layout',
    hideWebHiddenContent: 'Hide web-hidden content',
    ignoreLastPageBreak: 'Ignore last rendered page breaks',
    pdfToolbar: 'Built-in PDF toolbar',
    pdfNavigation: 'Navigation panel',
    defaultNavigationVisible: 'Open navigation by default',
    pdfThumbnails: 'Page thumbnails',
    pdfRotation: 'Initial rotation',
    pdfStreaming: 'Streaming',
    cjkFontFallback: 'CJK font fallback',
    identityFontRepair: 'Identity font repair',
    resizableColumns: 'Resizable columns',
    resizableRows: 'Resizable rows',
    textEncoding: 'Text encoding',
    workerThreshold: 'Worker threshold',
    textToolbar: 'Source metadata bar',
    lineNumbers: 'Show line numbers',
    virtualizeThreshold: 'Virtualization threshold',
    markdownVirtualizeThreshold: 'Markdown source threshold (0 keeps rendered)',
    maxRenderedLine: 'Rendered line limit',
    overscanLines: 'Overscan lines',
    archiveCache: 'Cache extracted entries',
    archiveEntryDownload: 'Allow entry downloads',
    maxArchiveSize: 'Maximum archive size',
    maxEntryPreview: 'Entry preview limit',
    cadRenderer: 'Renderer',
    cadFitMode: 'Initial fit',
    cadFitPadding: 'Drawing viewport ratio',
    includePaperSpace: 'Include paper space',
    lineWeightMode: 'Line-weight mode',
    bestFit: 'Smart bounds',
    nativeBounds: 'Native bounds',
    geoBasemap: 'Basemap',
    inferProjection: 'Infer projection',
    preferMapEngine: 'Prefer map engine',
    geoFitPadding: 'Bounds padding',
    modelUseWorker: 'Parse in a Worker',
    modelWorkerTimeout: 'Parse timeout',
    modelLinearUnit: 'Linear unit',
    modelUnitMillimeter: 'Millimeter (mm)',
    modelUnitCentimeter: 'Centimeter (cm)',
    modelUnitMeter: 'Meter (m)',
    modelUnitInch: 'Inch (in)',
    modelUnitFoot: 'Foot (ft)',
    modelDeflectionType: 'Linear deflection mode',
    modelDeflectionRatio: 'Bounding-box ratio',
    modelDeflectionAbsolute: 'Absolute value',
    modelLinearDeflection: 'Linear deflection',
    modelAngularDeflection: 'Angular deflection (rad)',
    preferOfficialDrawing: 'Prefer official drawing runtime',
    reloadHint: 'Applying safely refreshes the preview and restores your position.',
    noFormatSettings: 'This format is using its recommended defaults.',
    resetDefaults: 'Reset defaults',
    cancel: 'Cancel',
    applySettings: 'Apply settings',
    settingsApplied: 'Settings applied',
    settingsApplyFailed: 'Settings could not be applied. Check the values and try again.',
    integration: 'Integrate',
    toggleSourcePanel: 'Toggle file panel',
    quickSamples: 'Quick samples',
    quickSamplesHint: 'Open common formats',
    sampleFile: 'Sample file',
    collapse: 'Collapse',
    open: 'Open',
    address: 'URL',
    addressPlaceholder: 'Paste a file URL',
    linkPanelTitle: 'Open from URL',
    linkPanelHint: 'Supports relative paths, subdirectories, and full URLs',
    uploadPanelTitle: 'Upload from device',
    uploadPanelHint: 'Files stay in this browser and are never uploaded to a server',
    samplesPanelTitle: 'Sample library',
    preview: 'Preview',
    closePanel: 'Close control panel',
    chooseFile: 'Choose a file',
    openLocal: 'Open from this device',
    recentOpened: 'Recently opened',
    closeRecent: 'Close recently opened',
    showRecent: 'Show recently opened',
    openRecent: 'Open',
    dismissRecent: 'Remove from recently opened',
    reselectLocalFile: 'Browsers do not retain local files. Select “{name}” again.',
    unselected: 'No file selected',
    documentInfo: 'Document info',
    closeDocumentInfo: 'Close document info',
    fileSource: 'Source',
    filePath: 'Path',
    fileFormat: 'Format',
    previewActions: 'Preview actions',
    zoomControls: 'Zoom controls',
    zoomOut: 'Zoom out',
    zoomIn: 'Zoom in',
    resetZoom: 'Reset zoom',
    fitMode: 'Fit',
    fitDefault: 'Default',
    fitAuto: 'Auto',
    fitContain: 'Contain',
    fitCover: 'Cover',
    fitWidth: 'Width',
    fitHeight: 'Height',
    fitActual: '100%',
    fitScaleDown: 'Scale down',
    download: 'Download',
    downloadTitle: 'Download original file',
    print: 'Print',
    printTitle: 'Print complete rendered content',
    printDirect: 'Print now',
    printMask: 'Mask & print',
    printMaskTitle: 'Cover sensitive areas before printing',
    exportHtml: 'HTML',
    exportHtmlTitle: 'Export rendered HTML',
    watermark: 'Watermark',
    watermarkTitle: 'Toggle watermark',
    searchDocument: 'Document search',
    searchPlaceholder: 'Search this document',
    previousResult: 'Previous search result',
    nextResult: 'Next search result',
    closeSearch: 'Close search',
    closeMobileControls: 'Close mobile controls',
    openLinkSettings: 'Open URL settings',
    openSamples: 'Open sample files',
    uploadLocalFile: 'Upload a local file',
    searchCurrentDocument: 'Search this document',
    openMoreActions: 'Open more actions',
    reset: 'Reset',
    auto: 'AUTO',
    language: 'Language',
    theme: 'Theme',
    themeToLight: 'Switch to light mode',
    themeToDark: 'Switch to dark mode',
    integrationSnippet: 'Integration code',
    openIntegrationSnippet: 'View integration code',
    integrationSnippetHint: 'Open and copy a focused example',
    integrationSnippetDescription: 'Complete React integration example',
    closeIntegrationSnippet: 'Close integration code',
    copySnippet: 'Copy code',
    copiedSnippet: 'Copied'
  }
}

export function useDemoCopy(locale: Readonly<Ref<DemoLocale>>) {
  const getCopy = (nextLocale: DemoLocale): DemoCopy => demoCopyMap[nextLocale]
  const copy = computed(() => getCopy(locale.value))

  return {
    copy,
    getCopy
  }
}
